### ISSUE TITLE
Whitelist available device types

### ISSUE THREAD

**Issue by chrisys** [balenalabs/fold-for-covid-landing#108]
Limit the list of available device types to remove SKX2, any other custom device types or other devices with < 1GB RAM.

**Comment by alisondavis17** [comment]
Definitely remove: 
- SKX2
- Etcher Pro 
- CTI Orbitty
- CTI Spacely

Perhaps somebody else can review the list for devices to remove with < 1GB of RAM

**Comment by dtischler** [comment]
Also Remove:

- Nitrogen8MM DWE

The rest of the list appears to be capable of running the project, as all of them have a minimum of 1gb of RAM.
