### ISSUE TITLE
Download OS button giving "Server error" result

### ISSUE THREAD

**Issue by andrewnhem** [balenalabs/fold-for-covid-landing#124]
Using the Download OS button (https://api.balena-cloud.com/download) on https://foldforcovid.io/ leads to a server error.

Tried with Rpi3, 4, and a number of other devices all with the same result.

cc @iamsolankiamit @chrisys:  Did we change the way we get the images via API and haven't updated it for foldforcovid yet?

**Comment by iamsolankiamit** [comment]
Ohh, it's the `device-types/v1` issue. we are calling the older endpoint to fetch the images.

**Comment by andrewnhem** [comment]
Resolved per: https://www.flowdock.com/app/rulemotion/balenalabs/threads/zaozHMVTPpf9mqePmq-aaE8oRwa
