### ISSUE TITLE
Map icon should not be balena logo

### ISSUE THREAD

**Issue by chrisys** [balenalabs/fold-for-covid-landing#45]
Discuss with Alexandra possible alternatives to use here

**Comment by tmigone** [comment]
@sradevski, not sure if this was discussed already, but the new map icon (black dot) can be hard to notice if you zoom in a bit.  See example: https://imgur.com/bNvivxe
Would it be better if we switched it to the green (rgb(99, 186, 151))?

**Comment by sradevski** [comment]
@tmigone yeah we did discuss it and the green one is less obvious on satellite view. We can revisit once the other standing issues are done.
