### ISSUE TITLE
Limit SD card insert gif to certain device types

### ISSUE THREAD

**Issue by chrisys** [balenalabs/fold-for-covid-landing#64]
Right now the gif of inserting an SD card into a Pi is shown for all device types, this should be limited to Raspberry Pi only. We do have one for the Jetson Nano that's on the docs here that we can use for that device type also: https://www.balena.io/docs/img/gifs/jetson-insert-sd.gif

**Comment by sradevski** [comment]
@chrisys opened a PR to add the jetson nano one https://github.com/balenalabs/fold-for-covid-landing/pull/114 (Andrew posted a photo instead of a gif, that will help with loading speed of the page a bit), do we have anything else for other device types?

**Comment by chrisys** [comment]
@sradevski we don't have any others yet unless there are some on the docs we can use, but could we default to there being no gif if we don't have one? I think this is better than showing an incorrect one. We can use the existing Pi one for both Pi 3 and Pi 4.
