### ISSUE TITLE
Add social sharing links to last step of guides

### ISSUE THREAD

**Issue by chrisys** [balenalabs/fold-for-covid-landing#66]
As per Zeplin, add sharing icons to the last `Add as many devices as you can, and tell everyone you know!` step of each guide. I think for this we can use the same copy and actions as the Twitter / Facebook / LinkedIn buttons already on the site.

![Screenshot 2020-04-16 at 12 16 04](https://user-images.githubusercontent.com/521698/79449971-18925f80-7fdc-11ea-9a16-739b6ce56f8a.png)

![Screenshot 2020-04-16 at 12 15 12](https://user-images.githubusercontent.com/521698/79449882-eda80b80-7fdb-11ea-8310-84a76ef941fd.png)

**Comment by rahul-thakoor** [comment]
@chrisys 
 maybe add a note in step5 regarding how to access next devices? not everyone will figure to read the FAQ 👀
