### ISSUE TITLE
Add ability to add per-device-type notes/warnings to get started guides

### ISSUE THREAD

**Issue by chrisys** [balenalabs/fold-for-covid-landing#67]
Example: in our original instructions draft we had a warning that the Jetson Nano does not have on-board WiFi but we currently have no ability to specify that on a per-device basis.

**Comment by iamsolankiamit** [comment]
@chrisys now you can by adding the device type slug and its related info/steps here https://github.com/balenalabs/fold-for-covid-landing/blob/master/src/components/Guides.tsx#L291-L305
