### ISSUE TITLE
Change boinc team to Fold for Covid

### ISSUE THREAD

**Issue by rahul-thakoor** [balenalabs/fold-for-covid-landing#91]
The team is now called Fold for Covid
https://boinc.bakerlab.org/rosetta/team_display.php?teamid=18832

**Comment by rahul-thakoor** [comment]
@chrisys

**Comment by mpous** [comment]
BTW with the newest link the stats are not working! do you know why?

e.g. https://www.boincstats.com/stats/-1/team/detail/8ecbdda89d8db23cb750b3ba67985537
