### ISSUE TITLE
Add an FAQ explaining how to 'change bootup order' for laptop/desktop set up

### ISSUE THREAD

**Issue by Jazzagi** [balenalabs/fold-for-covid-landing#99]
Can we add an FAQ explaining how to do the following, as per the laptop/desktop set up instructions:

'Once complete, plug the USB stick into your computer, and power it on
If your computer does not automatically boot from the USB device, you may need to change its bootup order, or manually choose to boot from USB. Once the install process completes, the device will shut down and power off.'

We should also add a link to the FAQ to step 3 of the relevant getting started instructions

**Comment by andrewnhem** [comment]
@chrisys @rahul-thakoor @Jazzagi 

Here's a draft of something to add to the FAQ to address boot order issues. Feedback welcome!

## How do I make my old laptop boot from the USB stick?

If your spare laptop doesn't boot the USB stick immediately, fear not. You might have to restart the laptop and enter its BIOS settings. This is typically done by restarting your laptop, waiting for the motherboard loading screen to appear, and pressing either the DELETE key or a function (F1,F2, etc.) key depending on the brand and type of motherboard.

For instance, ASUS motherboards require you to press DELETE to access BIOS settings.

From there, access your Boot Options and move the USB drive to the first position (meaning it'll look there for an OS to boot first). Please consult your specific motherboard manual for more details about boot order.

---

cc: @iamsolankiamit @sradevski
